apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: qz0q05thq-python 
  janus-idp.io/tekton: qz0q05thq-python
  backstage.io/kubernetes-id: qz0q05thq-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qz0q05thq-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml