apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qz0q05thq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qz0q05thq-python 
  name: qz0q05thq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qz0q05thq-python 
